## Exercise 1

In [1]:
passwords = [
    "Kopi_Hitam#2024",     # 15 chars, mixed types
    "S3marang!City@",      # 14 chars, mixed types
    "Batik_P3kalongan!",   # 17 chars, mixed types
    "J4karta_M4ju2026!",   # 18 chars, mixed types
    "P4ssw0rd_Str0ng!",    # 16 chars, mixed types
    "short1!Aa",           # Too short (under 12 chars)
    "hanyahurufkecil!!",   # No uppercase, no numbers
    "HANYAHURUFBESAR123",  # No lowercase, no special chars
    "123456789012345",     # Only numbers
    "StrongPassword123"    # No special characters
]

# DUMMY PASSWORDS AI GENERATED

In [2]:
import re
pattern_pwd = r'(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[!@#$&*]).{12,}'

print('=== STRONG PASSWORD VALIDATOR ===\n')

for password in passwords:
    if re.search(pattern_pwd, password):
        print(f'{password:<20}: Valid')
    else:
        print(f'{password:<20}: Tidak Valid')

=== STRONG PASSWORD VALIDATOR ===

Kopi_Hitam#2024     : Valid
S3marang!City@      : Valid
Batik_P3kalongan!   : Valid
J4karta_M4ju2026!   : Valid
P4ssw0rd_Str0ng!    : Valid
short1!Aa           : Tidak Valid
hanyahurufkecil!!   : Tidak Valid
HANYAHURUFBESAR123  : Tidak Valid
123456789012345     : Tidak Valid
StrongPassword123   : Tidak Valid

In [3]:
import re
pattern_pwd = r'^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[!@#$&*]).{12,}'

print('=== STRONG PASSWORD VALIDATOR ===\n')

for password in passwords:
    if re.match(pattern_pwd, password):
        print(f'{password:<20}: Valid')
    else:
        print(f'{password:<20}: Tidak Valid')

=== STRONG PASSWORD VALIDATOR ===

Kopi_Hitam#2024     : Valid
S3marang!City@      : Valid
Batik_P3kalongan!   : Valid
J4karta_M4ju2026!   : Valid
P4ssw0rd_Str0ng!    : Valid
short1!Aa           : Tidak Valid
hanyahurufkecil!!   : Tidak Valid
HANYAHURUFBESAR123  : Tidak Valid
123456789012345     : Tidak Valid
StrongPassword123   : Tidak Valid

In [4]:
import re
pattern_pwd = r'^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[!@#$&*]).{12,}$'

print('=== STRONG PASSWORD VALIDATOR ===\n')

for password in passwords:
    if re.fullmatch(pattern_pwd, password):
        print(f'{password:<20}: Valid')
    else:
        print(f'{password:<20}: Tidak Valid')

=== STRONG PASSWORD VALIDATOR ===

Kopi_Hitam#2024     : Valid
S3marang!City@      : Valid
Batik_P3kalongan!   : Valid
J4karta_M4ju2026!   : Valid
P4ssw0rd_Str0ng!    : Valid
short1!Aa           : Tidak Valid
hanyahurufkecil!!   : Tidak Valid
HANYAHURUFBESAR123  : Tidak Valid
123456789012345     : Tidak Valid
StrongPassword123   : Tidak Valid

## Exercise 2

In [5]:
import re

with open("berita.txt", "r") as file:
    text = file.read()
    # print(text)

abbrevations = re.findall(r'\b[A-Z]{2,}\b', text)
print(list(set(abbrevations)))

['PENS', 'SK']

## Exercise 3

In [6]:
import re

with open('berita.txt', 'r') as file:
    text = file.read()
    # print(text)

orations = re.findall(r'orasi ilmiah[a-z :,]+(?=.)', text, re.IGNORECASE)
# print(orations)
for no, i in enumerate(orations, start = 1):
    print(f'{no}. {i}')

1. orasi ilmiah Pengembangan Technology Vector Control untuk Technology Electric Drive pada Dunia Industri Transportation Era Industri
2. orasi ilmiah Pengembangan Teknologi Kriptografi Berbasis Sinyal sebagai Inovasi Baru dalam Keamanan Jaringan Komunikasi di Indonesia
3. orasi ilmiah Penerapan Electrical Power Train untuk Mendukung Elektrifikasi Mesin Pertanian Padi Indonesia Kedepan
4. orasi ilmiah Sistem Mekatronika Cerdas: dari Teori, Menuju Kompetisi dan Implementasi
5. Orasi Ilmiah Peranan Komunikasi Sensor Nirkabel dalam Menunjang Program Indonesia yang mengangkat dua bidang utama, yakni pemetaan bencana dan pertanian

# Penugasan

## Exercise 4

In [7]:
import re

with open('berita.txt', 'r') as file:
    text = file.readline()
    print(text)

Surabaya, pens.ac.id – Sidang Terbuka Senat dalam rangka pengukuhan lima Guru Besar baru kembali dihelat pada Senin (24/2), di Ruang Auditorium Lt. 6 Gedung Pascasarjana Politeknik Elektronika Negeri Surabaya (PENS). Kegiatan yang dihadiri oleh jajaran direksi, civitas akademika, keluarga, serta tamu undangan tersebut menandai bertambahnya tenaga pendidik berkualitas di PENS. Adapun para Guru Besar yang dikukuhkan pada kegiatan ini, di antaranya empat dari Departemen Teknik Elektro, yakni Prof. Dr. Ir. Era Purwanto, M.Eng., Prof. Dr. Mike Yuliana, S.T., M.T., Prof. Dr. Arman Jaya, S.T., M.T., Prof. Mochammad Zen Samsono Hadi, S.T., M.Sc., Ph.D., serta Prof. Dr.Eng. Indra Adji Sulistijono, S.T., M.Eng. dari Departemen Teknik Mekanika dan Energi. Setelah pengukuhan para Guru Besar tersebut, diharapkan PENS terus memberikan kontribusi positif yang signifikan bagi kemajuan dunia pendidikan serta teknologi di Indonesia.

Input:
1. Prof. Dr. Ir. Era Purwanto, M.Eng., 
2. Prof. Dr. Mike Yuliana, S.T., M.T., 
3. Prof. Dr. Arman Jaya, S.T., M.T., 
4. Prof. Mochammad Zen Samsono Hadi, S.T., M.Sc., Ph.D., serta
5. Prof. Dr.Eng. Indra Adji Sulistijono, S.T., M.Eng.

Output:
['Arman Jaya', 'Era Purwanto', 'Indra Adji Sulistijono', 'Mike Yuliana', 'Mochammad Zen Samsono Hadi']

In [8]:
pattern = r'(Prof|Dr\.Eng|Dr|Ir)\.\s([A-Za-z]+(\s[A-Za-z]+)+),'

professors = re.findall(pattern, text)
print(professors)

professors = [professor[1] for professor in professors]
print(sorted(professors))

[('Ir', 'Era Purwanto', ' Purwanto'), ('Dr', 'Mike Yuliana', ' Yuliana'), ('Dr', 'Arman Jaya', ' Jaya'), ('Prof', 'Mochammad Zen Samsono Hadi', ' Hadi'), ('Dr.Eng', 'Indra Adji Sulistijono', ' Sulistijono')]
['Arman Jaya', 'Era Purwanto', 'Indra Adji Sulistijono', 'Mike Yuliana', 'Mochammad Zen Samsono Hadi']

### Analisis

1. Karena seluruh nama profesor terdapat di baris pertama, maka cukup untuk hanya membaca baris tersebut dengan fungsi *readline()*
2. Penggunaan *findall()* digunakan untuk mencari semua kata yang memenuhi pola, tidak berhenti di satu kata.
3. Pencarian regex yang dihasilkan berupa tuple, digunakan *list comprehension* untuk mengambil kata terkait (nama profesor) pada index 1.

### Bedah Pola Regex: 
1. **(Prof|Dr\.Eng|Dr|Ir)** : pengelompokan gelar dengan **| (vertical bar)** sebagai operator OR
2. **\.\s** : setelah gelar terdapat karakter titik dan spasi
3. **([A-Za-z]+(\s[A-Za-z]+)+),** : [A-Za-z]+ menemukan nama pertama, (\s[A-Za-z]+)+ iterasi grup sebanyak apapun untuk menangkap setiap kata pada nama. Tidak terbatas dengan nama yang memiliki dua kata, atau lima kata, atau berapapun.

## Exercise 5

In [10]:
import pandas as pd
import re

df = pd.read_csv('reviews_dataset_updated.csv')
df

                                      review_text sentiment
0  The product quality is amazing!!! I love it :)  positive
1   Terrible service... I will NEVER buy again!!!  negative
2        Pretty good (7/10), but could be better.   neutral
3              Absolutely fantastic experience!!!  positive
4               Not great :( had a lot of issues.  negative
5             I am so happy with this purchase <3  positive
6           Worst decision ever. Waste of $100!!!  negative
7           It works fine; nothing extraordinary.   neutral
8              Exceeded my expectations: 10/10!!!  positive
9        Disappointed... it broke after a week :(  negative

In [11]:
# Remove punctuation and digit
# Ref: https://www.geeksforgeeks.org/pandas/replace-values-in-pandas-dataframe-using-regex/
df['review_text'] = df['review_text'].replace(to_replace="[!:)./,(<$;\d]", value='', regex=True)

# Turn to lower case
# Ref: https://www.geeksforgeeks.org/pandas/python-pandas-series-str-lower-upper-and-title/
df['review_text'] = df['review_text'].str.lower()

df

                                 review_text sentiment
0  the product quality is amazing i love it   positive
1    terrible service i will never buy again  negative
2           pretty good  but could be better   neutral
3            absolutely fantastic experience  positive
4             not great  had a lot of issues  negative
5          i am so happy with this purchase   positive
6              worst decision ever waste of   negative
7        it works fine nothing extraordinary   neutral
8                  exceeded my expectations   positive
9        disappointed it broke after a week   negative

In [13]:
df.to_csv('cleaned.csv')